name: RPN Calculator Test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image: crystallang/crystal

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: cd rpn-calculator && shards init && shards install
    - name: Run tests
      run: crystal spec
